app/users/models.py
from app import db
from app.users import constants as USER
from datetime import datetime

# TODO: Include password field for manual (email) registration

class User(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(24), unique=True)
	
	# TODO: Check RFC for max length of an email
	email = db.Column(db.String(120), index=True, unique=True)
	about = db.Column(db.String(200))
	visibility = db.Column(db.Integer, default=USER.PRIVATE)
	rating_points = db.Column(db.Integer, default=0)
	rating_times = db.Column(db.Integer, default=0)
	join_date = db.Column(db.DateTime, default=datetime.utcnow())

	def __init__(self, name = None, email = None):
		self.name = name
		self.email = email

	def is_authenticated(self):
		return True

	def is_active(self):
		return True

	def is_anonymous(self):
		return False

	def get_id(self):
		return unicode(self.id)

	def __repr__(self):
		return '<User %r>' % (self.name)

app/users/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, TextAreaField, BooleanField
from wtforms.validators import Required, Length, Email, EqualTo
from flask.ext.babel import gettext
from app.users.models import User

# TODO: Use __init__ / validate methods for RegisterForm

class LoginForm(Form):
	openid = TextField('openid', validators=[Required()])

# Implement this after completing products module
class RegisterForm(Form):
	name = TextField('Name', validators=[Required()])
	email = TextField('Email', validators=[Required(), Email()])
	password = PasswordField('Password', validators=[Required()])
	confirm_password = PasswordField(
		'Repeat Password',
		validators=[
			Required(),
			EqualTo('password', message='Passwords must match')
		]
	)
	# optional: recaptcha = RecaptchaField()

# TODO: Check if entered username already exists

class EditForm(Form):
	name = TextField('Name', validators=[Length(min=4, max=24)])
	about = TextAreaField('About', validators=[Length(min=0, max=200)])
	visibility = BooleanField('Private Profile')

	def __init__(self, original_name, *args, **kwargs):
		Form.__init__(self, *args, **kwargs)
		self.original_name = original_name

	def validate(self):
		if not Form.validate(self):
			return False
		user = User.query.filter_by(name=self.name.data).first()
		if user is not None and user.name != self.original_name:
			self.name.errors.append(
				gettext('This name is alreay taken, please choose another one'))
			return False
		return True

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, \
	redirect, url_for
from flask.ext.login import login_user, logout_user, current_user, \
	login_required
from flask.ext.babel import gettext
from werkzeug import check_password_hash, generate_password_hash
from app import app, db, lm, oid, babel
from app.users.models import User
from app.users.forms import LoginForm, EditForm
import app.users.constants as USER

from string import letters
from random import sample

NICK_MAX_LENGTH = 24
mod = Blueprint('users', __name__, url_prefix='/users')

@lm.user_loader
def load_user(id):
	return User.query.get(int(id))

@mod.before_request
def before_request():
	g.user = current_user

@mod.route('/me')
@login_required
def home():
	return render_template(
		'users/profile.html', 
		user=g.user
	)

@mod.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
def login():
	if g.user is not None and g.user.is_authenticated():
		return redirect(url_for('index'))
	form = LoginForm()
	if form.validate_on_submit():
		return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
	return render_template(
		'users/login.html', 
		title='Sign In', 
		form=form, 
		providers=app.config['OPENID_PROVIDERS']
	)

@oid.after_login
def after_login(resp):
	if resp.email is None or resp.email == '':
		return redirect(url_for('users.login'))
	user = User.query.filter_by(email=resp.email).first()
	if user is None:
		nick = resp.nickname
		if nick is None or nick == '':
			nick = resp.email.split('@')[0][:NICK_MAX_LENGTH]
		n = User.query.filter_by(name=nick).first()
		
		# If the same nickname already exists, append random letters
		if n is not None:
			mod_nick = ('_' + ''.join(sample(letters, 10))) + nick
			nick = mod_nick[:NICK_MAX_LENGTH]
		user = User(name=nick, email=resp.email)
		db.session.add(user)
		db.session.commit()
	login_user(user)
	return redirect(request.args.get('next') or url_for('index'))

@mod.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('index'))

@mod.route('/get/<name>')
def get_by_name(name):
	user = User.query.filter_by(name=name).first()
	if user and user.name == g.user.name:
		flash(gettext('Trying to view your own profile. So smart.'))
		return redirect(url_for('users.home'))
	if user == None or user.visibility == USER.PRIVATE:
		flash(
			gettext('The profile you requested is private or doesn\'t exist.'))
		return redirect(url_for('users.home'))
	return render_template(
		'users/show_profile.html',
		user=user
	)

@mod.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
	form = EditForm(g.user.name)
	if form.validate_on_submit():
		g.user.name = form.name.data
		g.user.about = form.about.data
		g.user.visibility = 0 if form.visibility.data == True else 1
		db.session.add(g.user)
		db.session.commit()
		return redirect(url_for('users.home'))
	elif request.method != 'POST':
		form.name.data = g.user.name
		form.about.data = g.user.about
		form.visibility.data = True if g.user.visibility == 0 else False
	return render_template(
		'users/edit.html',
		form=form
	)

app/templates/users/edit.html
{% extends "base.html" %}

{% block content%}
<div class="container">
	<h2 class="page-header">Edit profile</h2>
	<form action="" method="POST" role="form">
		{{ form.hidden_tag() }}
		<div class="form-group">
			<label for="name">Name:</label>
			{{ form.name(class="form-control") }}
		</div>
		<div class="form-group">
			<label for="about">About:</label>
			{{ form.about(class="form-control") }}
		</div>
		<div class="form-group">
			<label for="visibility">Visibility:</label>
			{{ form.visibility }}
		</div>
		<button type="submit" class="btn btn-primary">
			<span class="glyphicon glyphicon-edit"></span> Edit
		</button>
	</form>
</div>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h2 class="page-header">Log in</h2>
	<form action="" method="POST" name="login" class="form-horizontal">
		{{form.hidden_tag()}}
		{% if error %}
		<div class=error><strong class="alert alert-danger">Error: </strong>{{ error }}</div>
		{% endif %}
		<div class="control-group">
			<label class="control-label" for="#openid">OpenID</label>
			<div class="controls">
				{{ form.openid(size = 40, class = "span4", value=providers[0].url) }}
			</div>
		</div>
		<br>
		<div class="control-group">
			<div class="controls">
				<input type="submit" class="btn btn-default" value="{{ _('Sign In') }}">
			</div>
		</div>
		<br>
	</form>
</div>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container well well-sm">
	<h2 class="page-header">Hi, 
		<small><strong id="username">{{ user.name }}</strong></small>
	</h2>
	<span>
		<label class="label label-info">Visibility: </label>
		<strong class="visibility">
			{% if user.visibility == 0 %}
				Private
			{% else %}
				Public
			{% endif %}
		</strong>
	</span>
	<br><br>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">About me:</h3>
		</div>
		<p class="panel-body">
			{{ user.about }}
		</p>
	</div>
	<a href="{{ url_for('users.edit') }}">
		<button type="submit" class="btn btn-primary">
			<span class="glyphicon glyphicon-edit"></span> Edit Profile
		</button>
	</a>
</div>
{% endblock %}

app/templates/users/show_profile.html
{% extends "base.html" %}

{% block content %}
<div class="container well well-sm">
	<h2 class="page-header">{{ user.name }}'s profile</h2>
	<span>
		<label class="label label-info">Visibility: </label>
		<strong class="visibility">
			Public
		</strong>
	</span>
	<br><br>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">About {{ user.name }}:</h3>
		</div>
		<p class="panel-body">
			{{ user.about }}
		</p>
	</div>
</div>
{% endblock %}