app/products/views.py
from flask import Blueprint, request, render_template, flash, g, session, \
	redirect, url_for, send_from_directory
from flask.ext.login import login_user, logout_user, current_user, \
	login_required
from flask.ext.babel import gettext
from werkzeug import check_password_hash, generate_password_hash
from app import app, db, lm
from app.products.models import Product, category
from app.users.models import User
from app.products.forms import UploadForm, EditForm, DeleteForm
import math
import os

from werkzeug.utils import secure_filename

# TODO: Use flash() to display error messages

mod = Blueprint('products', __name__, url_prefix='/products')

def allowed_file(filename):
	return '.' in filename and \
		filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']

@lm.user_loader
def load_user(id):
	return User.query.get(int(id))

@mod.before_request
def before_request():
	g.user = current_user

@mod.route('/')
@mod.route('/get/page/<int:page>')
def home(page=1):
	product_count = Product.query.count()
	products = Product.query.paginate(page, per_page=12).items
	return render_template(
		'products/all.html',
		products=products,
		pages=int(math.ceil(product_count / float(12))),
		current_page=page
	)
	

@mod.route('/id/<int:id>')
def get_by_id(id):
	product = Product.query.filter_by(id=id).first()
	if product == None:
		flash(gettext('Product not found!'))
		return redirect(url_for('index'))
	return render_template(
		'products/product.html',
		product=product
	)

@mod.route('/search/<query>')
def search(query):
	pass

@mod.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_product():
	user_id = User.query.filter_by(name=g.user.name).first().id
	form = UploadForm()
	if form.validate_on_submit():
		imagefile = request.files[form.imagefile.name]
		filename = None
		if imagefile and allowed_file(imagefile.filename):
			filename = secure_filename(imagefile.filename)
			imagefile.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
		product = Product(
			form.name.data, form.price.data, user_id,
			description=form.description.data,
			quantity=form.quantity.data,
			imagefilename=filename)
		db.session.add(product)
		db.session.commit()
		flash(gettext('Product successfully added!'))
		return redirect(url_for('products.home'))
	return render_template(
		'products/upload.html',
		form=form
	)

@mod.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_product(id):
	form = EditForm()
	if form.validate_on_submit():
		pass
	return render_template(
		'products/edit.html',
		form=form
	)

@mod.route('/delete/id/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_product(id):
	form = DeleteForm()
	if form.validate_on_submit():
		pass
	return render_template(
		'products/delete.html',
		form=form
	)

# Serving images
@mod.route('/image/<filename>')
def give_image(filename):
	return send_from_directory(app.config['UPLOAD_FOLDER'],
			filename)

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, \
	redirect, url_for
from flask.ext.login import login_user, logout_user, current_user, \
	login_required
from flask.ext.babel import gettext
from werkzeug import check_password_hash, generate_password_hash
from app import app, db, lm, oid, babel
from app.users.models import User
from app.users.forms import LoginForm, EditForm
import app.users.constants as USER

from string import letters
from random import sample

NICK_MAX_LENGTH = 24
mod = Blueprint('users', __name__, url_prefix='/users')

@lm.user_loader
def load_user(id):
	return User.query.get(int(id))

@mod.before_request
def before_request():
	g.user = current_user

@mod.route('/me')
@login_required
def home():
	return render_template(
		'users/profile.html', 
		user=g.user
	)

@mod.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
def login():
	if g.user is not None and g.user.is_authenticated():
		return redirect(url_for('index'))
	form = LoginForm()
	if form.validate_on_submit():
		return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
	return render_template(
		'users/login.html', 
		title='Sign In', 
		form=form, 
		providers=app.config['OPENID_PROVIDERS']
	)

@oid.after_login
def after_login(resp):
	if resp.email is None or resp.email == '':
		return redirect(url_for('users.login'))
	user = User.query.filter_by(email=resp.email).first()
	if user is None:
		nick = resp.nickname
		if nick is None or nick == '':
			nick = resp.email.split('@')[0][:NICK_MAX_LENGTH]
		n = User.query.filter_by(name=nick).first()
		
		# If the same nickname already exists, append random letters
		if n is not None:
			mod_nick = ('_' + ''.join(sample(letters, 10))) + nick
			nick = mod_nick[:NICK_MAX_LENGTH]
		user = User(name=nick, email=resp.email)
		db.session.add(user)
		db.session.commit()
	login_user(user)
	return redirect(request.args.get('next') or url_for('index'))

@mod.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('index'))

@mod.route('/get/<name>')
def get_by_name(name):
	user = User.query.filter_by(name=name).first()
	if user and user.name == g.user.name:
		flash(gettext('Trying to view your own profile. So smart.'))
		return redirect(url_for('users.home'))
	if user == None or user.visibility == USER.PRIVATE:
		flash(
			gettext('The profile you requested is private or doesn\'t exist.'))
		return redirect(url_for('users.home'))
	return render_template(
		'users/show_profile.html',
		user=user
	)

@mod.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
	form = EditForm(g.user.name)
	if form.validate_on_submit():
		g.user.name = form.name.data
		g.user.about = form.about.data
		g.user.visibility = 0 if form.visibility.data == True else 1
		db.session.add(g.user)
		db.session.commit()
		return redirect(url_for('users.home'))
	elif request.method != 'POST':
		form.name.data = g.user.name
		form.about.data = g.user.about
		form.visibility.data = True if g.user.visibility == 0 else False
	return render_template(
		'users/edit.html',
		form=form
	)

app/templates/base.html
<!doctype html>
<html>
<head>
	<title>{{ title }} - ZBay</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
	{% include "navs.html" %}
	<div class="error-block">
		{% include "flash.html" %}
	</div>

	{% block content %}
	{% endblock %}
	{% include "footer.html" %}
	<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
</body>
</html>

app/templates/flash.html
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	{{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/templates/footer.html
<footer class="navbar navbar-inverse navbar-fixed-bottom">
	<div class="container">
		<div class="navbar-right navbar-text">Made by Team Mocha</div>
	</div>
</footer>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	{% if g.user and g.user.is_authenticated() %}
	<h2>Welcome, <strong>{{ g.user.name }}</strong></h2>
	{% else %}
	<h2>Sign in to get started!</h2>
	<a href="{{ url_for('users.login') }}">
		<button type="submit" class="btn btn-primary btn-lg">Login</button>
	</a>
	{% endif %}
</div>
{% endblock %}

app/templates/navs.html
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<!-- align with the right, its a bit higher than the right links  -->
		<a href="{{ url_for('index') }}" class="navbar-brand">Zbay</a>
		<ul class="nav navbar-nav navbar-right">
			{% if g.user and g.user.is_authenticated() %}
			<li>
				<a href="{{ url_for('products.upload_product') }}">
					<button class="btn btn-primary navbar-btn nav-btn-custom">
						<span class="glyphicon glyphicon-upload"></span> Upload product</button>
				</a>
			</li>
			<li class="navbar-text"><a href="/index" class="navbar-link">
				<span class="glyphicon glyphicon-home"></span> Home</a>
			</li>
			<li class="navbar-text"><a href="{{ url_for('users.home') }}">
				<span class="glyphicon glyphicon-user"></span> Profile</a>
			</li>
			<li class="navbar-text"><a href="{{ url_for('users.logout') }}">Logout</a></li>
			{% else %}
			<a href="{{ url_for('users.login') }}">
				<button class="btn btn-primary navbar-btn navbar-right nav-btn-custom">Login</button>
			</a>
			{% endif %}
		</ul>
	</div>
</nav>